### ISSUE TITLE
question  regarding batch_size

### ISSUE THREAD

**Issue by zhouhao957** [HuguesTHOMAS/KPConv-PyTorch#107]
Hello, I use my own data set. If the number of each model point is different, can I use it? Or is batch_size only 1

**Comment by HuguesTHOMAS** [comment]
Yes every dataset used in this repo has a variable number of input points, so you can copy our dataset implementation for your data.

**Comment by zhouhao957** [comment]
Sorry, I can't find out which function it is. Can you tell me
Thanks again！！

**Comment by HuguesTHOMAS** [comment]
You can ignore this `batch_size=1` in the training loader, this has nothing to do with the actual batch size.

To use your own dataset, you have to create a new dataset class like `datasets/S3DIS.py` or `datasets/ModelNet40.py`. Follow the python file and make changes so that is load your own data instead. For your information, the actual batch size is controlled in this function:

https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/1cd3742fc57e5ba9d21f7909c78a05a971781351/datasets/S3DIS.py#L263-L400
