### ISSUE TITLE
first_features_dim 

### ISSUE THREAD

**Issue by ginobilinie** [HuguesTHOMAS/KPConv-PyTorch#123]
I'd like to ask why the settings of first_features_dim in training S3DIS dataset on tf and pytorch version are different. In tf version, it is set to 64 by default, but in pytorch version, it is set to 128.

**Comment by HuguesTHOMAS** [comment]
It is due to the way I defined Resnet bottleneck layers. There are two ways to see it:

1) You have input features with dimension D, you upsample them to the size 2D for the shortcut and downsample them to the size D/2 for the convolution. 

2) You have input features with dimension D, you keep them for the shortcut and downsample them to the size D/4 for the convolution. 

The ratio between the shortcut and convolution is always 4. I changed the way to define resnet layers in PyTorch to version 2. Therefore the initial features are now double the size as in tf. It is not exactly equivalent but makes more sense in my opinion.

**Comment by ginobilinie** [comment]
Thank you so much.

**Comment by ginobilinie** [comment]
Dr. Thomas, can I ask what's the benefit of switching to version 2 in pytorch? I think that's the reason of different memory cost since the decoder stage may cost more memory if you set the first_features_dim to 128.

**Comment by HuguesTHOMAS** [comment]
Well, it is more of a convenience to understand more easily what happens inside the network. The difference in memory cost should not be very high as it only impact the upsampling mlp layers

**Comment by ginobilinie** [comment]
Thanks, Dr. Thomas. You help me a lot, I appreciate it.
