### ISSUE TITLE
Do you split the scenes into chunks?

### ISSUE THREAD

**Issue by Pixie412** [HuguesTHOMAS/KPConv-PyTorch#185]
Hi,

Thanks for sharing the code! I have a question regarding the input format. It seems that you take the whole as input without splitting it into blocks nor do you sample points from the blocks as pointnet++. https://github.com/yanx27/Pointnet_Pointnet2_pytorch/blob/master/data_utils/S3DISDataLoader.py
Am I right?

**Comment by HuguesTHOMAS** [comment]
Hi @Pixie412,

No, you are not right. You can have a look at the paper where I explain that the scene is not divided beforehand, but that we sample points in small spheres across the dataset to create the network input. This is similar to pointnet++, but instead of always having the same cubic blocks, we have spherical blocks that can be picked anywhere

**Comment by Pixie412** [comment]
Thanks! Got it.
