### ISSUE TITLE
Working with smaller (8GB) GPUs

### ISSUE THREAD

**Issue by LucHayward** [HuguesTHOMAS/KPConv-PyTorch#189]
Hi Hugues

Firstly thanks again for releasing your code and some pretrained models.
I've been working on this for a few days trying to see if it was possible to use your pretrained models in my own research (for transfer learning). We are trying to do few shot learning where we have maybe 5-30% of a scene labelled, so starting with your model pretrained (or as a feature extractor) is far more effective than training from scratch (at least with Pointnet++). But I was constantly getting CUDA out of memory issues (at random, likely due to the randomly changing number of points in the spheres at each batch).

My initial thought was to reduce the ```batch_num``` from ```6``` to ```1``` but **I see in other issues you recommend never going below ```batch_num=3```. Can you explain why not?** My understanding is that this controls the number of spheres per batch (on average), during inference/validation surely this can be set to any value (that fits in VRAM)? (This is actually an issue in all pointcloud models when pointwise distances need to be computed that momentarily requires about 40% extra RAM I've found but that's besides the point)

I think the correct solution for me is to retrain the model myself using either  a shallower network and/or smaller ```in_radius``` and higher ```first_subsampling_dl``` parameter as you suggest in #47 .

**Comment by HuguesTHOMAS** [comment]
Hi @LucHayward,

This is a very interesting problem and I would be happy to help.

> My initial thought was to reduce the batch_num from 6 to 1 but I see in other issues you recommend never going below batch_num=3. Can you explain why not?

The key to this issue is in your next sentence: "_this controls the number of spheres per batch __(on average)___". When you pick random spheres across the dataset, the number of points per sphere can vary a lot:

It could look like this:
```
Nb of points per sphere
..................
....
..............
..
..............................
..........
```

The principle behind our variable batch size is that we want to fix the total number of points per batch, by setting a limit and stacking sphere point clouds until we reach the limit. This limit is found during the calibration phase to match the average `batch_num` value you chose). Here is what the batches look like with `batch_num = 3`

```
             Max point per batch limit   ->   |       batch_num     n_points
................../..../...............       |           3            39
..../.................../...../.......        |           4            38
................../.......................    |           2            42
../......./............../........./........  |           5            44
................................              |           1            32
........../.........../.................      |           3            40
                                                    AVG = 3      small variation
```

If you reduce the limit to have only one point cloud per batch, here is what it will look like:
```
limit  ->  |                        batch_num     n_points
...........|......                      1            18
....       |                            1             4
...........|............                1            24
../.....   |                            2             8
...........|.....................       1            33
.......... |                            1            10
                                  AVG = 1      high variation
```

Do you see how the variations in point cloud size will affect your batch size on the GPU? `batch_num` has no incidence on memory consumption, only `n_points` matters. In the end, with `batch_num=1`, you might still encounter CUDA out of Memory issues because of some spheres that will contain a lot of points. I find that usually, with `batch_num=3`, the limit is not too much above the maximum nb of points in a sphere.

**Comment by LucHayward** [comment]
To close this out, a big thank you for the help and for the excellent model. I ultimately did not have time to retrain your model from scratch on a different dataset (although this could be interesting). However for your interest, I found pertaining to be helpful generally though not significantly, and your model far outperforms both Pointnet++ and PointTransformer on my data.
