### ISSUE TITLE
question about s3dis preprocessing

### ISSUE THREAD

**Issue by guochengqian** [HuguesTHOMAS/KPConv-PyTorch#19]
hi, @HuguesTHOMAS 
Thanks for your amazing work! Effective and Efficient. 
I have some questions w.r.t the data preprocessing of s3dis. Could you help me figure it out?

1. why do you train and evaluate on the subsampled S3DIS, not the original (full-resolution) one? Is that a common practice?
https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/9bae9a3a2a04a3675fa4ec6e5993711438a32e9f/datasets/S3DIS.py#L171
you subsample (fuse the points inside 0.03 m spheres). Is `0.03 m` a common practice also? 

2. what's the function of `potentials` and `pot_tree`? 
my understanding is taht potential is used as a way to sample the centre points of a sphere. Is that correct? what's the difference between `use_potentials` and `random sample`? 
https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/9bae9a3a2a04a3675fa4ec6e5993711438a32e9f/datasets/S3DIS.py#L779
https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/9bae9a3a2a04a3675fa4ec6e5993711438a32e9f/datasets/S3DIS.py#L240
3. Why do you use sphere-sampled S3DIS? Are you the first one to use it? PointNet, PointCNN, DGCNN all used pillar based sampling. However, I do believe sphere-sampling preserves better spatial information and appreciate sphere-sampling. 

4. why do you stack zeros in the feature input?  why do you only use RGB + Z not RGB+xyz? 
https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/9bae9a3a2a04a3675fa4ec6e5993711438a32e9f/datasets/S3DIS.py#L409

**Comment by HuguesTHOMAS** [comment]
Hi @guochengqian,

Thank you for your interest in my work, here are some answers to your questions.

1. When processing point clouds, it is very common to subsample them regularly, in particular if the density of point is irregular (like on Semantic3D dataset for example). In general, the size of the subsampling should be chosen big enough to limit the amount of point you have to deal with, but small enough to keep the geometric details. For S3DIS, 2 or 3 cm seemed a good trade-off to me.
And by the way,the subsampling method I use is a grid-subsampling so it fuses the points inside 0.03 m voxels and not spheres.

2. Yes you are correct, potentials are used to choose the input center regularly in the dataset. This sampling method will not be affected by density variations. I also have a random sampling method that simply choose randomly N points per class in the dataset. This second method balances the classes but is affected by density variations.

3. I agree with you that using input spheres instead of input pillars is better in theory, but I don't think it makes much of a difference in the results. I don't know if I am the first one to use it, I would assume probably not.

4. Actually I stack ones in the feature input, this is explained in the paper in the experiments section. X and Y so not make any sense in a dataset where the orientation of room objects could be any direction. However, The Z value is the height of the points and actually has a geometrical meaning. It will remain the same whatever the orientation of the dataset.

**Comment by guochengqian** [comment]
Great! Thanks for your detailed explanation. 
best, 
guocheng
