### ISSUE TITLE
Wrong with "import cpp_wrappers.cpp_neighbors.radius_neighbors as cpp_neighbors" in common.py file

### ISSUE THREAD

**Issue by Luan-Zhaoliang** [HuguesTHOMAS/KPConv-PyTorch#3]
H! Thank you for implementing the PyTorch version!

I met some error when I run 'common.py'.
My environment is mac, I have done "sh compile_wrappers.sh", but I can't get the function "radius_neighbors", Could you give me some suggestions for that? Thanks a lot!
![image](https://user-images.githubusercontent.com/63129571/81487855-9eab6a00-9259-11ea-9142-e22c71ac72eb.png)

**Comment by HuguesTHOMAS** [comment]
Hi @Luan-Zhaoliang,

I am sorry but I never used mac environment, so I have no idea how to solve your problem. 

When running `sh compile_wrappers.sh`, what do you see in the console? You should get a compiled file like: `radius_neighbors.cpython-36m-x86_64-linux-gnu.so` in the folder `cpp_wrappers/cpp_neighbors`. If you don't, then there must be some C++ error due to your environment.

**Comment by Luan-Zhaoliang** [comment]
> radius_neighbors.cpython-36m-x86_64-linux-gnu.so

**Comment by Luan-Zhaoliang** [comment]
> Hi @Luan-Zhaoliang,
> 
> I am sorry but I never used mac environment, so I have no idea how to solve your problem.
> 
> When running `sh compile_wrappers.sh`, what do you see in the console? You should get a compiled file like: `radius_neighbors.cpython-36m-x86_64-linux-gnu.so` in the folder `cpp_wrappers/cpp_neighbors`. If you don't, then there must be some C++ error due to your environment.

Hi，Thanks for your reply. I have checked it, but can't find file'radius_neighbors.cpython-36m-x86_64-linux-gnu.so'. Maybe it is not suitable for Mac environment.

**Comment by ooodragon94** [comment]
I also can't find "radius_neighbors" file
did you happen to find a solution? 

thanks
