### ISSUE TITLE
Suggestion of code simplification.

### ISSUE THREAD

**Issue by shangguan9191** [HuguesTHOMAS/KPConv-PyTorch#34]
I am comparing different algorithm implemented on Pytorch for 3D point cloud, I want to make Kpconv works well.
i found that is way more complicated to implement Kpconv for my own dataset in this repo and takes substantial amount of time. 

i would suggest this https://github.com/valeoai/LightConvPoint code style. In this repo, the achitecture is already KPconv. this only thing that is need is KPconv layer. However, i do not how to code it.

**Comment by HuguesTHOMAS** [comment]
Hi @shangguan9191,

Thank you for your comment, I know that my code is not the best. I optimized it for my usage, and not for code simplicity. This is why I design my network architecture from parameters and I do not hardcode it in the python scripts. This is also why I use complex data_loaders, which may be hard to understand but in the end are more efficient.

You also have to understand that small details can translate into big implementation differences. For example, I use spherical neighborhood, while the repo your are referring to only use KNN. Using spherical neighborhood is harder, because you do not always have the same number of neighbors. So I have to use implementation tricks like the shadow neighbors. 

This is the reason why it would be very hard to code a real KPConv layer in this LightConv repo. However, if you forget the spherical neighborhood and want to implement a simple KPConv with KNN, it should be pretty easy. Have a look at this class:

https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/94b1d87e17ec339e2aad049ce5d5d175b9cd0db1/models/blocks.py#L143

It is very similar to the implementation of the different convolutions in LightConvPoint. YOu should be able to something from that.

Best,
Hugues
