### ISSUE TITLE
Missing inference on some points of the points cloud

### ISSUE THREAD

**Issue by fazzi1992** [HuguesTHOMAS/KPConv-PyTorch#41]
Hi, @HuguesTHOMAS 
Thanks for your work! 
We are trying to use the library for the cloud segmentation on our own dataset.
We have some problems with the inference. We have the following output for a particular points cloud
![image](https://user-images.githubusercontent.com/30315172/93197436-eb450b80-f74b-11ea-8be5-0cb195d7ca88.png)

You can see in blue the ground and in green the vegetation. 
As you can notice we have some points that are not classified (gray ones).
For completeness, the parameters chosen (for training and inference) are the same parameters that you use for the S3DIS dataset. 
Do you have some suggestions in order to have a complete classified points cloud?

**Comment by HuguesTHOMAS** [comment]
The result you show here is very strange. 

Some ideas that pop out of my mind: Do you re-project the classification on the original points? Because the network usually processes a subsampled version of the input clouds. How many classes do you have in your training? Do you have an "unclassified" class?

Best,
Hugues

**Comment by fazzi1992** [comment]
Thank you for the suggestions. The error was related to our datasets and missing labels.
