### ISSUE TITLE
Training Time

### ISSUE THREAD

**Issue by hudingchang** [HuguesTHOMAS/KPConv-PyTorch#43]
Hello, HuguesTHOMAS, thanks for your great work and the release of code.

I notice that the training time of the first epoch is pretty longer than the training time of the subsequent epochs by using the code of tensorflow version. I guess it is because you have cached some batchs of data in the first epoch, then the processing of the following epochs can be very quick, is that true?

But when performing the same operation (caching some batchs of data) in pytorch, I cannot find such a significant time reduction.

Can I reimplement this operation with pytorch?

Thanks for your advice. @HuguesTHOMAS

**Comment by HuguesTHOMAS** [comment]
I am not sure to understand your question, what do you want to reimplement exactly?

**Comment by hudingchang** [comment]
Thanks for your reply.

I'd like the training process of pytorch as fast as tensorflow because I find the training of pytorch code is slower than tensorflow code after (except) the first epoch.

**Comment by HuguesTHOMAS** [comment]
Are you sure you use the same parameters. The default architecture is deeper in the Pytorch version of the code.

**Comment by hudingchang** [comment]
Thank you, I know where the problem is now.

**Comment by hadilou** [comment]
Sorry to reopen this.  I am also experiencing the same issue. As example see [issue 141](https://github.com/HuguesTHOMAS/KPConv-PyTorch/issues/141) During training/testing, the first batch of every epoch lasts longer than the following ones. It seems to be because  PyTorch recreates the [data loader ](https://pytorch.org/docs/stable/data.html#torch.utils.data.DataLoader) and relaunches the workers. Setting `persistent_workers=True` doesn't seem to have any effect . Do you have a work around ? @HuguesTHOMAS @DCNSW . Thanks!

**Comment by HuguesTHOMAS** [comment]
Hi @hadilou,

The numbers shown in the log are not right, because the time measurement goes from the end of the last batch to the end of this batch. But between the end of the last batch and the beginning of this batch, some other stuff happens that takes some time. Therefore the first batch time appears longer than it really is. You can try to measure the time from the beginning of the batch to the end of the batch and compare, the first batch time should be much more similar to the others.
