### ISSUE TITLE
Can this work be run under Cuda 9.0?

### ISSUE THREAD

**Issue by lwx-bupt** [HuguesTHOMAS/KPConv-PyTorch#44]
I've tried to run this code using gpu version of pytorch 1.5. However it says the driver version is too old. 
AssertionError: 
The NVIDIA driver on your system is too old (found version 9000).
Please update your GPU driver by downloading and installing a new
version from the URL: http://www.nvidia.com/Download/index.aspx
Alternatively, go to: https://pytorch.org to install
a PyTorch version that has been compiled with your version
of the CUDA driver.
I've tried to downgrade to pytorch 1.1 to cope with cuda 9.0 but the module "get_worker_info" couldn't be found in that version. 
I'm running it on a shared server so I don't want to reinstall cuda or Nvidia drivers. Are there any possible workarounds? Thanks a lot!

**Comment by HuguesTHOMAS** [comment]
I think it is a bad idea to use an older version of Pytorch, because I assume `get_worker_info` is not the only module that will be missing. You could have unexpected errors anywhere. If you really don't have any other solution, then you will have to modify the implementation everywhere there is a bug. For example here it's simple because the `get_worker_info` is just a debug function you can delete it with no problem. But I cannot ensure that everything will work for the rest of the code.

If you work on a shared server, the best solution in my opinion is to use docker containers so that you can have your own version of nvidia drivers, CUDA, and Pytorch.

Otherwise try to search online if its possible to install Pytorch with older CUDA version, but I don't think that will be easy.

Good lucj with your issue.
Hugues

**Comment by lwx-bupt** [comment]
Thanks, switched to Cuda 10.2 instead~
