### ISSUE TITLE
Scannet preprocessing and training

### ISSUE THREAD

**Issue by mutianxu** [HuguesTHOMAS/KPConv-PyTorch#49]
Hi @HuguesTHOMAS,

Due to the data preprocessing may goes into many details in your work, transferring to ScanNet scenes from S3DIS training script is really non-trivial.

So could you please give us some tips of adapting the S3DIS script to ScanNet?

Highly appreciate!

**Comment by HuguesTHOMAS** [comment]
Hi @mutianxu,

I really use the same idea for Scannet and S3DIS, the difference is that the scenes are smaller and you have a large number of them instead of only 6. But really I use the same input preprocessing into spheres etc.

For more details, you can have a look at the original KPConv repo in Tensorflow. Compare the S3DIS and Scannet dataset scripts to see the differences.

**Comment by mutianxu** [comment]
@HuguesTHOMAS ，
Thank you much. I will try.
