### ISSUE TITLE
Performance in comparison with Tensorflow implementation

### ISSUE THREAD

**Issue by nejcd** [HuguesTHOMAS/KPConv-PyTorch#51]
Hi Hugues, 

great work. I was wondering if there is any performance difference between Tensorflow and Torch implementation? How so that you have made also Torch implementation? I guess the majority of PointCloud related models have been implemented in Tensorflow mainly because of PointNet, but I am getting feeling that people are migrating to Torch more and more (maybe do TF2?). 

Cheers, Nejc

**Comment by HuguesTHOMAS** [comment]
Hi @nejcd,

Sorry for the late answer, I have been cleaning the repo of old issues and I just realized I never answered your question. The difference between using PyTorch and Tensorflow is mostly about your personal preference. In recent years, PyTorch seems to have gained more interest in the research community because it is easier to manipulate, but it could change in the future. 

In the case of KPConv, the performances are similar between the two repos, but I personally switch to PyTorch for my more recent experiments, for the comfort of implementation and the easier code understanding.

Best luck with your own project,
Hugues
