### ISSUE TITLE
online training on ScanNet dataset?

### ISSUE THREAD

**Issue by chronbird** [HuguesTHOMAS/KPConv-PyTorch#54]
Hi @HuguesTHOMAS ，

I managed to reproduce KPConv-Pytorch on Scannet recently. The implementation is just similar to S3DIS' one.
Now the problem is: can I train training samples on-the-fly? In other words, I want load ply and generate KDTree in __getitem__() rather than pre-load them into memory. Is this possible when I want to use potential?
My concern is when there are very large amount of training samples, it may not feasible to pre-load them all into memory. 
Thanks.

**Comment by HuguesTHOMAS** [comment]
I understand your concern. It is possible, yes, but it will require you to modify many portions of the code. You have two choices when it comes to the way you will do it:

- The most simple choice is to keep the potential in memory. You don't keep the points in memory, so you should have enough space to keep the potentials. Therefore you only have to modify the part of the codes where the KDTree are used, and load them everytime you need them. As Scannet has relatively small scenes, it should not be a problem to load the KDTrees on the fly especially if you work with a SSD

- The other choice is when you don't even have enough space to keep the potentials in memory. Then you have to save them along with the KDTrees, and load them with them. But you will have to keep the minimum potential of each scan in memory to decide which scan are to be chosen at a given training step. In this case, you could run into more difficulties, as more parts of the code would be impacted. And you would have to handle the multi-processing file access, for example by forcing threads to wait that another thread has finished updating and saving a potential file, before being able to load it. This really would be more complex.

**Comment by chronbird** [comment]
Thanks so much for your kind advice. I want to try the first one. As you said, scenes in Scannet are smaller compared to in other datasets, can I directly train the whole scene without running kdtree? If not, how about also both creating kdtrees and querying points on the fly? Thanks.

**Comment by HuguesTHOMAS** [comment]
I would not advise to create KDTree on the fly as building the tree can take some time. But, honestly, I never tried so it could work, especially since the scene are not that big.

You can also train with the whole scenes directly, but then you will have to use a larger `first_subsampling_dl` to reduce the number of points per scene. If you use input sphere, you can use a lower `first_subsampling_dl` and thus have more details. This is a choice you have to make. My intuition is that using sphere should help the overall performances, but my method is not the best performing one on Scannet so I could be wrong. YOu can try to experiment yourself and see what leads to the best results.

Best,
Hugues

**Comment by FengqiLiu1221** [comment]
I have met some problem when I implemented the dataset of ScanNet. Can you share your dataset with me? Thanks a lot!

**Comment by HuguesTHOMAS** [comment]
I am sorry, I never implemented Scannet dataset for PyTorch. I only did it back when I was using Tensorflow.

**Comment by sangrockEG** [comment]
@chronbird 
Could you share your code regarding the ScanNet dataset?
It will be greatly appreciated.
