### ISSUE TITLE
deformable or rigid

### ISSUE THREAD

**Issue by YuXing3d** [HuguesTHOMAS/KPConv-PyTorch#61]
Hi Hugues,

At first, thank you for your great work! 

I tried your KPConv on my own dataset for semantic segmentation and noticed that deformable convolution didn't achieve better performance than rigid form but cost much more time. Do you have any general suggestions on these two types of convolution? For example, on what kind of point clouds is deformable version a better choice (may contribute better results)?

Best,
Yuxing

**Comment by HuguesTHOMAS** [comment]
Hi @YuXing3d,

Thanks for your interest in my work. It is very hard to answer this question because even I am not entirely sure when deformable convolution is better than rigid convolution. It seems from my experience that in complex datasets with many different shapes, the deformable can help. But there is not a huge difference anyway. 

If your goal is not to study the idea of deformable convolution, I think the best, for now, is to use the rigid KPConv. When (or if) more works are published on deformable convolutions, we might gain a better understanding of it.

Best luck with your work.
Hugues

**Comment by YuXing3d** [comment]
Thank you for your explanation. So I can use rigid convolution with an easy mind, which is really efficient and much more memory-friendly. Good luck & best wishes!
