### ISSUE TITLE
Is Subsampling Necessary? 

### ISSUE THREAD

**Issue by Arjun-NA** [HuguesTHOMAS/KPConv-PyTorch#62]
Hi Hughues,

I am Arjun. I had contacted previously for understand KP Conv. While I was working to create a pytorch version for the dataset Dales. I could find that subsampling is actually not giving much reduction in the file size from original to the newly saved ply file. I wonder if subsampling is necessary, Is it possible to avoid it and still have KPConv work properly. 

Basically I just want to know if subsampling affects KPConv other than the fact that it is used by the KDtree creation. I also plan to use the original points for creating KDtree.

Thank you,
Arjun.

**Comment by HuguesTHOMAS** [comment]
Hi Arjun, 

The subsampling is not only important to reduce the total number of points. It is also important to reduce the number of points in the radius neighborhoods. If you have some part of your dataset, which has a very high density of points, then it affects the performances tremendously. That being said, if you know that the density of points in your dataset is relatively stable, and you won't have some areas with a lot of packed points, then you don't really need the subsampling. You just need to adjust the parameter "first_subsampling_dl" approximately to the minimal distance between points in your original dataset, so that the first convolution radius is adapted.

Best,
Hugues

**Comment by Arjun-NA** [comment]
Thank you for the information. 

I was having some trouble getting the calibration working without subsampling. Anyways I wanted one more insight for now. Is having a radius of 20 okay? because I see a portion 
```pot_dl = self.config.in_radius / 10```
Does pot dl have to be less than 1?

Also please correct me if I am wrong in saying that the dl is the min sampling distance, i.e, the minimum distance between points after sampling. 
Thanks.
