### ISSUE TITLE
kernel_point_optimization_debug

### ISSUE THREAD

**Issue by JihaoLee** [HuguesTHOMAS/KPConv-PyTorch#65]
Hi, thank you for your code. I find there is a mistake in `kernel_point_optimization_debug` function in `kernel` folder `kernel_points.py` .

>    https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/master/kernels/kernel_points.py#L434

Perhaps, the iter can not reach 10,000. If you use `best_k = np.argmin(grad_norms[-1, :])`, maybe  `best_k` is all 0. Is my understanding correct?

And about the calibration function in [https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/master/datasets/S3DIS.py#L1038](url). Could you explain the implementation process in detail?  

Thank you very much! Looking forward to your reply!

**Comment by HuguesTHOMAS** [comment]
I @JihaoLee,

Thanks a lot for spotting this mistake. Indeed, in the event of a break, the last row of grad_norms would be all zeros and the argmin would not do anything. I will correct this error shortly.

About the calibration process. Here is the thought behind its implementation. We want to calibrate the "batch_limit" so that the average batch size is close to the chosen `config.batch_num`, and we want to calibrate the "neighborhood_limits" to have a reduced and consistent memory consumption (think of this fact: if the number of neighbors in only one convolution is very high, we have to define the whole neighbors matrix big enough to contain it, but it is a big wast as most of the other neighborhoods are smaller). If you don't use the neighborhood calibration, the size of the neighbors matrix (and thus the memory consumption) changes at every step and is not bounded, which can lead to OOM errors frequently.

These two calibrations are data-dependant, we cannot know in advance the right values, as they depend on the dataset. They also depend on some parameters of your model, including the input radius, convolution radius, first subsampling dl, etc. So we have to compute them every time we start a new experiment. For faster prototyping, I save the computed limit values in a file and load them if they were already computed before. If they were not you enter into the "redo" portion of the code which is where the computation happens. FOr the neighbors, we simply create a histogram counting how many neighborhoods have a particular size, then we chose the size that cut the histogram at a given percentile. For the batch limit, we use a feedback control loop mechanism: try a value for the batch limit, see if the corresponding batch number is higher or lower than the target value, increase or decrease the batch limit in accordance (this is the equivalent of a simple proportional controller). 

Hope this helps
Best,
Hugues
