### ISSUE TITLE
changing the radius of the sphere and kernel point

### ISSUE THREAD

**Issue by 12z34x** [HuguesTHOMAS/KPConv-PyTorch#66]
Hi, thank you for your codes firstly. And I have some problems now. According to my understanding, each 3D point will create a small sphere, and K kernel points in it. Now, I want to change the radius of the sphere and kernel point, so that each 3D point will have more neighbours and one kernel point will influence more points.  So, how can I realize this? When I change the train_dataset.py (in_radius,conv_radius), I will get "limit" errors, and program will die soon.
And can you explain this "limit" set  in detail? why you set this limitation ?
The following information is the error.

Check batch limit dictionary
"potentials_1.500_0.030_2": ?
Check neighbors limit dictionary
"0.030_0.150": ?
"0.060_0.300": ?
"0.120_0.600": ?
"0.240_1.200": ?
"0.480_2.400": ?

Step     1  estim_b = 0.10 batch_limit =    101
Step     7  estim_b = 0.52 batch_limit =    701
Step    18  estim_b = 0.85 batch_limit =   1801
Step    26  estim_b = 0.94 batch_limit =   2601
Step    32  estim_b = 0.97 batch_limit =   3201

**Comment by HuguesTHOMAS** [comment]
Hi @12z34x,

Thanks for your interest in this work. If I understand correctly you want the convolution radius to be bigger so that more neighbors are influenced. For this you have a simple parameter to modify:

https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/94b1d87e17ec339e2aad049ce5d5d175b9cd0db1/train_S3DIS.py#L105-L106

The radius is measured relative to the subsampling cell size. So if you want more points in your convolution, simply use a bigger value. Be careful though because it will increase the memory consumption and could lead to OOM errors if your GPU is not big enough.

Now if you increase the radius of the convolution, you also want to increase the influence radius of each kernel points accordingly:

https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/94b1d87e17ec339e2aad049ce5d5d175b9cd0db1/train_S3DIS.py#L111-L112

Otherwise, some part of your convolution sphere will not be under the influence of any kernel point. See figure 53 on page 114 of my Ph.D. thesis: https://pastel.archives-ouvertes.fr/tel-02458455/document

Eventually for more details about the neighbors limit, please refer to this previous issue: https://github.com/HuguesTHOMAS/KPConv-PyTorch/issues/65#issuecomment-740790383
