### ISSUE TITLE
DataParallel - Multi GPUs Implementation

### ISSUE THREAD

**Issue by fazzi1992** [HuguesTHOMAS/KPConv-PyTorch#67]
Hi @HuguesTHOMAS,
thank you for your repository. We are using it for our segmentation task and it works very well.
Now, we want to reduce the time for the training and so we are trying to use DataParallel to run the net on Multi GPUs.
Our first trail is to use DataParallel only for the KPConv layer (both in the in the SimpleBlock and in the ResnetBottleneckBlock) but we obtain the error:
"RuntimeError: CUDA error: an illegal memory access was encountered"
It seems that the error is in the custom gather method that it is used to make faster the backwards.
Do you have any hints? 
Thanks,
Giovanni

**Comment by HuguesTHOMAS** [comment]
Hi @Fazzy,

thanks for your interest in the code. Your question is very tricky because multi-GPU parallelization is not trivial in the case of KPConv. I have given this a little bit of thought before and the major trick is that we do not have a batch dimension. The common way to parallelize between multiple GPUs is to separate the batch into multiple parts and this is exactly what DataParallel does. From the documentation:

> This container parallelizes the application of the given module by splitting the input across the specified devices by chunking in the batch dimension (other objects will be copied once per device).

I think the reason why your error happens in the gather function is that DataParallel splitter the batch data (feature matrix, point matrix, and neighborhood matrix) along their first dimension, which would not be respecting the delimitation of the different point clouds. So some point cloud would end up splitter between two GPUs, and therefore some neighbor indices would be pointing to nothing. Furthermore, the neighbor indices would not even be right because splitting the points in, let's say, four parts would change their indices so the neighborhood matrix would have to be updated.

Now that being said, our data is still splittable, just not in a standard way, so we need to custom the batch creation. I think the easiest way to do it is to add the batch dimension to our data and handle the batch splitting ourselves in the input pipeline. For each GPU, we create a sub-batch in the same way as the batches are created now. Then we stack them in the batch dimension so that DataParallel can split them.

**Comment by HuguesTHOMAS** [comment]
However, I have to warn you that the GPU is not the only bottleneck for the training time. The CPU has also quite a lot to do. All the subsampling and neighbors are computed in the CPU parallelized input pipeline. This input pipeline is not that fast, it can keep up with one GPU but if you have 4 GPUs then you will need a beast CPU to keep up with them and feed the data in time. In S3DIS.py, you can find some remains of the printing functions I used to debug the computing speeds when I implemented this repo.

Use `debug_worker = True` for example here:

https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/bb0ea445b168463d4b7dffee8b61c235775fc33a/datasets/S3DIS.py#L242

Or `debugT = True` here:
https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/bb0ea445b168463d4b7dffee8b61c235775fc33a/datasets/S3DIS.py#L449-L451

If you are limited by the CPU then you might have to implement more efficient c++ wrappers, but I feel like I did a pretty good job with that so I don't know how much you can gain there.
