### ISSUE TITLE
How to modify the cpp_wrappers part for label with 'float32' dtype

### ISSUE THREAD

**Issue by liuyueyun** [HuguesTHOMAS/KPConv-PyTorch#68]
Hi @HuguesTHOMAS ，
    Thank you for your work very much. 
    I recently trained on the S3DIS dataset with your code, it performs very well. However, when I try to make a custom on my own dataset, whose label is a 3 dimentional array for one point with type 'float32'. And it asserts error:
RuntimeError: Error converting input classes to numpy arrays of type int32
    Since I don't use c++， I simply change all the "int" related to classes in cpp_wrappers to "float", and all the "NPY_INT" related to classes to "NPY_FLOAT". And rebuild it. Still, it asserts error:
RuntimeError: Error converting input classes to numpy arrays of type int32

could you please give me some tips about this situation, is there anything else I should channge？

**Comment by HuguesTHOMAS** [comment]
Hi @liuyueyun,

Thanks for your interest in the code. From what you are telling me I assume the error happens here:

https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/bb0ea445b168463d4b7dffee8b61c235775fc33a/datasets/S3DIS.py#L736-L750

As you can see, the `grid_subsampling` function has three input arrays: points, features, and labels. The points array is the one that is subsampled, the features array holds any float32 value associated with the points, and the labels array holds any int32 value associated with the points. What you have to understand is that the names "features" and "labels" are not important, they just mean that the corresponding array is treated in a certain way: the values of the features array, being continuous float32 values, are averaged at the new subsampled points, while the values of the labels array are chosen in a voting manner at the new subsampled points (because having one point of class 2 and one of class 4 does not mean that the new subsampled point should be class 3, it would not make any sense).

So now that you understand the function, I think the solution to your problem is to use the grid subsampling function, but concatenate your float32 labels to the color values:

```
sub_points, sub_features = grid_subsampling(points,
                                            features=np.hstack((colors, labels)),
                                            labels=None,
                                            sampleDl=dl)
```

And if I were you I would not call them "labels" if they are float32, keep the name that describes them the best like normals or offsets.

**Comment by liuyueyun** [comment]
@HuguesTHOMAS yes，the grid_subsampling function is where the error occurs, sorry I didn't describe it clearly. Thank you for your reply, it solves my problem. As you remind me they are offsets, I should not call them labels. Thank you again.
