### ISSUE TITLE
Per-point xyz feature differs layer by layer

### ISSUE THREAD

**Issue by honggudrnjs** [HuguesTHOMAS/KPConv-PyTorch#79]
Hi :) I have a question while studying your implementation.
Conceptually, I thought that xyz coordinate values are kept the same for all the layers except unavoidable case like downsampling.
However, I checked both batch feature (it might include z information, right?) and query points for each layer and found that
scale differs layer by layer significantly. Could you explain why this happens?

**Comment by HuguesTHOMAS** [comment]
Hi @honggudrnjs,

I have trouble understanding what you mean because batch.features are only available for the first layer of the network, while batch.points are available for every layer. if you look at the batch.points (save them and show them in CloudCompare for example), you will see that their scale is not altered from one layer to the other. only the resolution changes

**Comment by honggudrnjs** [comment]
Oh! I just found that batch.features directly means latent features. As you said, xyz point features can be extracted using batch.points. Thanks. 

But I have one more question though... When downsampling occurs in the midst of network flow, is there a way to get point indices that are selected for downsampling. batch.input_inds seems not working in the customized batch sampler provided by your code.

**Comment by HuguesTHOMAS** [comment]
The downsample indices between each layer are stored in the list of tensors called `batch.pools`
