### ISSUE TITLE
Run bug

### ISSUE THREAD

**Issue by missbook520** [HuguesTHOMAS/KPConv-PyTorch#9]
Hi,Thanks for your great work!
I follow your instruction to run train_S3DIS.py,but it alaways stop at epoch 16 or epoch 17,I set the maxepoch is 500,and change first_subsampling_dl =0.03 to 0.08
could you help me? Thank you!
![11](https://user-images.githubusercontent.com/48777650/83246849-48d13e80-a1d5-11ea-82e1-8953c01dc755.png)

**Comment by HuguesTHOMAS** [comment]
Hi @missbook520,

This is a strange error. I don't see any error message, so that means it could come from one of the c++ extension, or maybe from the parallel workers in the input pipeline. I dont have much time to look into that but I will try to next week. 

In the meantime, if you have manage to track down the error at a specific part of the code, it could help me to know how to fix it (You can use num_workers=0 so that the input pipeline is not parallelized, the code will be slower, but you will know exactly where is fails)

Best,
Hugues

**Comment by missbook520** [comment]
Thanks for your reply!
I have set num to 0（input_threads = 0）, and I am running this program under the win platform, I will debug the specific location where this problem occurs
